// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © NDO-42

//@version=5
indicator("Volatility Contraction", overlay=false)

// Define variables
period = input.int(5, "Price Action Period")
vol_period = input.int(5, "Volume Period")
threshold = input.int(10, "Threshold Line (%)")
breakout_bool = input.bool(true, "Plot Breakouts")

// Calculate the high-low range of the recent period based on open and close values
h = if open > close
    open
else
    close

l = if close < open
    close
else
    open

// Calculate the range of the defined period
recent_high = ta.highest(h, period)
recent_low = ta.lowest(l, period)
recent_range_pc = (recent_high - recent_low) / recent_low *100

// Calculate a moving average of the volume and define a break of the MA from below the consolidation threshold
vol_ma = ta.sma(volume, vol_period)
breakout = volume > vol_ma and ta.crossover(recent_range_pc, threshold)

breakout_plot = if breakout_bool
    breakout
else
    na

// Plot
hline(threshold, title="Threshold", color=color.black, linestyle=hline.style_dashed)
plot(recent_range_pc, title="Price Range", color=color.blue, linewidth=1)
plotshape(breakout_plot, "Breakout", shape.diamond, location = location.bottom, color = color.lime)