study(title = "NR4 / NR7 + Inside Bar", overlay = true)

nr4 = (tr <= tr[1]) and (tr <= tr[2]) and (tr <= tr[3])
     and (high<high[1] and low>low[1])

nr7 = nr4 and (tr <= tr[4]) and (tr <= tr[5]) and (tr <= tr[6])
     and (high<high[1] and low>low[1])

profit = (nr4[1] or nr7[1] ) and ((high > high[1] and low>low[1] and close>high[1] ) or (high<high[1] and low < low[1] and close<low[1] ))
loss = (nr4[1] or nr7[1] ) and ( (high > high[1] and ( close<high[1] or low < low[1] )) or (low < low[1] and (close>low[1]or high > high[1]) ))


barcolor( nr4 ? blue : na, offset = 0, editable = true, title = "NR4")
barcolor( nr7 ? fuchsia : na, offset = 0, editable = true, title = "NR7")

plotshape(nr4, title= "NR4", location=location.abovebar, color=white, style=shape.arrowdown, text="NR4")
plotshape(nr7, title= "NR7", location=location.belowbar, color=white, style=shape.arrowup, text="NR7")

plotshape(profit, title= "profit", location=location.abovebar, color=white, style=shape.arrowdown, text="profit")
plotshape(loss, title= "loss", location=location.belowbar, color=white, style=shape.arrowup, text="loss")