// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © ZenAndTheArtOfTrading
// @version=6
indicator("Relative ATR Volatility", overlay = false)

// User inputs
atrLength       = input.int(14, "ATR Length")
windowLength    = input.int(100, "Rolling Window Length")
topPercent      = input.float(80, "Top Percentile")
bottomPercent   = input.float(20, "Bottom Percentile")

// Indicator values
atrValue        = ta.atr(atrLength)
bottomThreshold = ta.percentile_nearest_rank(atrValue, windowLength, bottomPercent)
topThreshold    = ta.percentile_nearest_rank(atrValue, windowLength, topPercent)
centerThreshold = ta.percentile_nearest_rank(atrValue, windowLength, 50)
isBottomX       = atrValue <= bottomThreshold
isTopX          = atrValue >= topThreshold
atrRatioUpper   = atrValue / topThreshold
atrRatioLower   = atrValue / bottomThreshold

// Visuals
topGradient     = 0.0
bottomGradient  = 0.0

if (isTopX and topThreshold > 0)
    topGradient := (atrValue - topThreshold) / topThreshold

if (isBottomX and bottomThreshold > 0)
    bottomGradient := (bottomThreshold - atrValue) / bottomThreshold

topGradient         := math.min(topGradient, 1.0)
bottomGradient      := math.min(bottomGradient, 1.0)

topTransparency     = 90 - int(topGradient * 80)
bottomTransparency  = 90 - int(bottomGradient * 80)

atrPlot             = plot(atrValue, "ATR", color = color.white)
bottomPlot          = plot(bottomThreshold, "Bottom X% Threshold", color = color.green, display = display.pane)
topPlot             = plot(topThreshold, "Top X% Threshold", color = color.red, display = display.pane)
centerPlot          = plot(centerThreshold, "Median ATR", color=color.gray, display=display.none)

topAtrFillValue     = isTopX ? atrValue : na
bottomAtrFillValue  = isBottomX ? atrValue : na

topAtrFillPlot      = plot(topAtrFillValue, "Top ATR Fill", display = display.none)
bottomAtrFillPlot   = plot(bottomAtrFillValue, "Bottom ATR Fill", display = display.none)

fill(topAtrFillPlot, topPlot, color = color.new(color.red, topTransparency))
fill(bottomAtrFillPlot, bottomPlot, color = color.new(color.green, bottomTransparency))

plot(atrRatioUpper, "ATR Ratio (vs Upper Band)", color.red, display=display.status_line)
plot(atrRatioLower, "ATR Ratio (vs Lower Band)", color.green, display=display.status_line)